version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
before_build:
- ps: Copy-Item C:\projects\3D_Engine\$env:CONFIGURATION\3dEngine.exe C:\projects\3D_Engine\Game\.
build:
  verbosity: minimal
artifacts:
- path: 3dEngine\3D_Engine\Game
  name: 3dEngine
before_deploy:
- ps: Copy-Item C:\projects\$env:CONFIGURATION\3dEngine.exe C:\projects\3dEngine\3D_Engine\Game\.
deploy:
- provider: GitHub
  release: 3dEngine
  auth_token:
    secure: 2DzcApzRS0yghJ1z/Md4szz/1MJUnIfA1utoePAp5NMxkunBmpZ8YLgcIogdIeV9G/KP/izHxUROolV5sr12qWvTlBJ2WBTNjXY6xh5LIhU=
  draft: true
