version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
build:
  verbosity: minimal
before_package:
- ps: Copy-Item C:\projects\3dEngine\3D_Engine\$env:CONFIGURATION\3dEngine.exe C:\projects\3dEngine\3D_Engine\Game\.
artifacts:
- path: 3D_Engine\Game
  name: 3dEngine
deploy:
- provider: GitHub
  description: 3dEngine
  auth_token:
    secure: Lh1VhoJumvjo1vVrwJYN+6A2X2QH0Ax1V3GjE9IyNLAdcZgfG6kEEhy9p/ntKjn5
  draft: true
