version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
build:
  verbosity: minimal
before_package:
- ps: Copy-Item C:\projects\3dEngine\3D_Engine\$env:CONFIGURATION\3dEngine.exe C:\projects\3dEngine\3D_Engine\Game\.
artifacts:
- path: 3D_Engine\Game
  name: 3dEngine
deploy:
- provider: GitHub
  release: 3dEngine
  auth_token:
    secure: 4c949d2ee33b730733e93f705efc6b05dedb5e6b
  draft: true
